### ISSUE TITLE
Update historical fire perimeters layer

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/alaska-wildfires#12]

**Comment by cstephen** [comment]
The historical fire perimeters layer has been updated in GeoServer and the production Alaska Wildfire Explorer tool. The procedure for this was a bit different than in the past. From this website:

https://fire.ak.blm.gov/predsvcs/maps.php

It appears that the historical fire perimeters Shapefile is no longer available, so what I did was download the `AlaskaFireHistory_Polygons_1940_2021.zip` GeoDatabase (listed under the "Data (zipped filegeodatabases)" section) and converted it into a GeoPackage using GDAL with the following command:

```
ogr2ogr -f GPKG AlaskaFireHistory.gpkg AlaskaFireHistory_Polygons.gdb
```

GeoServer understands GeoPackages just as well as Shapefiles, so I uploaded `AlaskaFireHistory.gpkg` to GeoServer, added it as a Store, and created a Layer from the store. The styles that worked for the Shapefile work for the GeoPackage, too, without any changes.
