### ISSUE TITLE
Footer Update

### ISSUE THREAD

**Issue by MikeDelue** [ua-snap/alaska-wildfires#121]
Email from Micah, PI on the EPA project: "Can we please add UAA Institute for Circumpolar Health Studies, UW, EPA logos (or it looks like maybe you have it in text) and the EPA grant info at the bottom so we can be sure to credit all the contributors and funding?"

Action: Update footer text.

This tool was developed by the [Scenarios Network for Alaska and Arctic Planning](https://www.snap.uaf.edu/) in collaboration with the [Alaska Climate Adaptation Science Center](https://akcasc.org/), the [UAA Institute for Circumpolar Health Studies](https://www.uaa.alaska.edu/academics/college-of-health/departments/population-health-sciences/institute-for-circumpolar-health-studies), and the [University of Washington](https://www.washington.edu/). Development was partially funded by [EPA Grant Number R840479](https://cfpub.epa.gov/ncer_abstracts/index.cfm/fuseaction/display.abstractDetail/abstract_id/11349). SNAP is a research group in the [International Arctic Research Center](https://uaf-iarc.org/) at the [University of Alaska Fairbanks](https://uaf.edu/uaf/).

**Comment by brucecrevensten** [comment]
Closed by #122
